### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by guizmaii** [aws/aws-msk-iam-auth#102]
Hi @mkoch1,

Is it possible for you to release a new version maybe, please?

I'm particularly interested in these changes:
- https://github.com/aws/aws-msk-iam-auth/commit/7ee52e8055164fdf06074808d62d4064e40dc99e
- https://github.com/aws/aws-msk-iam-auth/commit/5a1def58e527a8107cd0f91561450d3b4ffb4a5a

Also, I think that it'd be good if this PR was merged before the new release:
- https://github.com/aws/aws-msk-iam-auth/pull/93

Thanks 🙏 
Jules

**Comment by mkoch1** [comment]
New version 1.1.6 is already committed, assume that will be released and published. @plazma-prizma can you pls confirm?

**Comment by hhkkxxx133** [comment]
Hello,

We have released the latest version 1.1.6 which includes both #99 and #101.

Thanks!
