### ISSUE TITLE
Support for credential rotation?

### ISSUE THREAD

**Issue by azuroff** [aws/aws-msk-iam-auth#12]
Our data security team mandates that IAM secret keys be rotated every 90 days.  Does the library have support for that, or is that something on the roadmap?

**Comment by gokul2411s** [comment]
Yes, the library supports updates to the client's IAM credentials (including secret keys, but also access keys and session tokens). The library itself uses standard AWS credential providers which pick up the new credentials automatically. Hope this answers your question.

**Comment by gokul2411s** [comment]
Please let us know if there are any other questions or concerns.
