### ISSUE TITLE
Update on release 1.1.7 schedule

### ISSUE THREAD

**Issue by s-ifti** [aws/aws-msk-iam-auth#123]
Hello,

I wanted to see when can we expect a release to support `awsRoleExternalId` as a property for jaas.config

This enhancement (https://github.com/aws/aws-msk-iam-auth/pull/109) is already merged in main but looks like was merged post 1.1.6 release.

This is an important security enhancement, as  assume role without check for external id is not a good idea.

Thanks

**Comment by hhkkxxx133** [comment]
Hello, we have released 1.1.7 which includes the commit #109. Thanks!
