### ISSUE TITLE
MSK connector with IAM authentication not working in Glue console

### ISSUE THREAD

**Issue by ankurshri** [aws/aws-msk-iam-auth#138]
MSK connector with IAM authentication not working in Glue console
When I try to create Kafka connector in Glue console it shows IAM authentication option but it does not let me save the connector
Seems a bug
Could not find any mention of MSK connector with IAM authentication for Glue in AWS Documentation

**Comment by shrutimehrotra7** [comment]
ankurshri@ This looks like a bug of Glue console. Can you please cut a ticket to Glue console team instead?
