### ISSUE TITLE
Support for AWS SSO credentials

### ISSUE THREAD

**Issue by rtimush** [aws/aws-msk-iam-auth#16]
If I try to use a CLI profile configured with SSO, I get the following error:
```
...com.amazonaws.auth.profile.ProfileCredentialsProvider@2232acfe: No AWS profile named 'my-profile'...
```

This is probably happening because the library uses AWS SDK v1, while SSO credentials are only supported in the AWS SDK v2.

**Comment by sayantacC** [comment]
You are right. Loading credentials for a SSO based profile is a missing capability as of now. 
We will look into how we can add support for a SSO based profile. 
There are different ways forward for us: 
1. Upgrading aws-msk-iam-auth to use AWS SDK v2.
1. Or use just the SSO capability from AWS SDK v2 (see https://github.com/aws/aws-sdk-java/issues/2434). 


In the meanwhile, I will update the README to call out the missing capability.

**Comment by sayantacC** [comment]
Update: 
I have coded up using sso in a branch https://github.com/aws/aws-msk-iam-auth/tree/sso. Sadly, I have not had the chance to test it out yet. I will look at getting it tested. Feel free to give it a spin.

**Comment by sayantacC** [comment]
Closing this issue as the fix for it has been merged.
