### ISSUE TITLE
Can not access msk with latest version (2.1.0)

### ISSUE THREAD

**Issue by hoalt14** [aws/aws-msk-iam-auth#168]
Hi friends,

My version of MSK cluster is 3.5.1, and my client is an EC2 instance with IAM role attach exactly policy

I can't work the SASL mechanism = AWS_MSK_IAM with version 2.1.0 (It can not load credentials)

Here is the error logs:
ERROR org.apache.kafka.common.errors.SaslAuthenticationException: An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: Failed to find AWS IAM Credentials [Caused by software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[AwsCredentialsProviderChain(credentialsProviders=[EnvironmentVariableCredentialsProvider(), SystemPropertyCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(sections=[])), ContainerCredentialsProvider()])]) ...

But i can work with version 1.1.1

Why? Maybe SDKv2 not working? Help me explain this issue.

Thank you!

**Comment by jvdadda** [comment]
Hi @hoalt14 , indeed, I miss something during migration, the fix is in PR: https://github.com/aws/aws-msk-iam-auth/pull/169

**Comment by jogilsang** [comment]
> Hi @hoalt14 , indeed, I miss something during migration, the fix is in PR: #169

still not working 2.1.0
but, It works in 2.0.3

My environment is as follows
- MSK Version (Apache Kafka) : 3.5.1
- Kafka Client : https://downloads.apache.org/kafka/3.7.0/kafka_2.12-3.7.0.tgz

**Comment by jvdadda** [comment]
@jogilsang The fix is not deployed inside the 2.1.0, so it is "normal" to have it, a maintainer should initiate a release

**Comment by kloometropolis** [comment]
Will this fix be released soon?

**Comment by yermulnik** [comment]
We're hitting the same. Can the release be expedited please?

**Comment by guanlinz** [comment]
Hi there,
Facing the same issue, here

**Comment by sidyag** [comment]
Fix has been released.
