### ISSUE TITLE
2.1.1 release includes SaslAuthenticationException regression

### ISSUE THREAD

**Issue by jamielwhite** [aws/aws-msk-iam-auth#180]
In #143, I reported an issue in which the first re-authentication failed for the `OAUTHBEARER` mechanism. This issue was resolved  in release 2.0.3 for the case when `awsRoleArn` was provided. When I upgraded our apps from 2.0.3 to 2.1.1, I noticed our apps were restarting every hour due to a `SaslAuthenticationException: Session too short` error. The difference between the behavior now vs in #143 is that the failure occurs after one hour, not after 15 minutes when the role first expires.

I reported this in a [comment](https://github.com/aws/aws-msk-iam-auth/issues/176#issuecomment-2179608638) on a related issue for the case where `awsRoleArn` is not provided, but since that error also occurs in 2.0.3 I've created this as a separate issue.

```
security.protocol=SASL_SSL
sasl.mechanism=OAUTHBEARER
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required awsRoleArn="<role arn>" awsStsRegion="<region>";
sasl.login.callback.handler.class=software.amazon.msk.auth.iam.IAMOAuthBearerLoginCallbackHandler
```

**Comment by james1miller93** [comment]
We're also seeing this using version `2.1.0`. Looking back through the comments from @jamielwhite, it seems we're running our services in exactly the same way (pods in a kubernetes cluster with iam credentials assigned via irsa roles). As mentioned above, the error is causing our apps to restart.

**Comment by sidyag** [comment]
I think this PR will fix this. Can you test with it? https://github.com/aws/aws-msk-iam-auth/pull/182

**Comment by jamielwhite** [comment]
I'll test it out, but since we aren't using `awsProfileName` I'm not sure if that branch is going to be hit.

**Comment by sidyag** [comment]
Interesting. The configuration is provided with `awsRoleArn`? Let me try and reproduce it in that way.

**Comment by jamielwhite** [comment]
I tested the jar from the PR and confirmed it still results in the "Session too short" error after 1 hour with `awsRoleArn`.

**Comment by sidyag** [comment]
I added the fix for `awsRoleArn` https://github.com/aws/aws-msk-iam-auth/pull/183

I think something similar is happening for default creds. Will try to fix that today.

**Comment by jamielwhite** [comment]
I pulled down the code from #183 and tried out the JAR, and unfortunately it still resulted in the same error after an hour.

**Comment by sidyag** [comment]
Is that with `awsRoleArn` or with default? The fix for default is on its way.

**Comment by jamielwhite** [comment]
It's with `awsRoleArn`. I inspected the jar and double-checked it includes the new `asyncCredentialUpdateEnabled` property being set to `true`.

**Comment by sidyag** [comment]
Okay. Found the issue. It is a documentation problem.

Try with the following configurations:

```
security.protocol=SASL_SSL
sasl.mechanism=OAUTHBEARER
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required awsRoleArn="<role arn>" awsStsRegion="<region>";
sasl.login.callback.handler.class=software.amazon.msk.auth.iam.IAMOAuthBearerLoginCallbackHandler
sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMOAuthBearerLoginCallbackHandler
```

**Comment by jamielwhite** [comment]
With `awsRoleArn` and the addition of `sasl.client.callback.handler.class`, I'm able to run it longer than 1 hour without any errors 🎉

**Comment by jamielwhite** [comment]
The case without `awsRoleArn` is also working for longer than 2 hours now. Thanks for the fix and documentation!

**Comment by james1miller93** [comment]
Thank you for your work on resolving this @sidyag.
Do you know when a release tag is likely to be published with the fix?
