### ISSUE TITLE
Unable to produce message on MSK with IAM config - ( org.apache.kafka.common.errors.TimeoutException: Topic 'test' not present in metadata after 60000 ms)

### ISSUE THREAD

**Issue by agurha** [aws/aws-msk-iam-auth#22]
Hi - I recently setup MSK with following config 

MSK Config 

auto.create.topics.enable=true

IAM Config

Role with policy attached 

Policy 1: 

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "kafka-cluster:CreateTopic",
                "kafka-cluster:DescribeCluster",
                "kafka-cluster:ReadData",
                "kafka-cluster:DescribeTopic",
                "kafka-cluster:DescribeGroup",
                "kafka-cluster:Connect",
                "kafka-cluster:WriteData"
            ],
            "Resource": [
                "arn:aws:kafka:*:accountid:topic/*/*/*",
                "arn:aws:kafka:*:accountid:group/*/*/*",
                "arn:aws:kafka:us-east-1:accountid:cluster/test/cluster-uuid"
            ]
        }
    ]
}

Policy 2:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "kafka:DescribeClusterOperation",
                "kafka:DescribeConfigurationRevision",
                "kafka:ListClusters",
                "kafka:DescribeConfiguration",
                "kafka:ListNodes",
                "kafka:DescribeCluster",
                "kafka:GetBootstrapBrokers",
                "kafka:ListClusterOperations"
            ],
            "Resource": "*"
        }
    ]
}

Created a user msktest with the above policies and generated AccessKey and Secret. 

Further on created an aws profile 

When I perform the following command I get a proper response back 

aws kafka describe-cluster --region us-east-1 --cluster-arn "arn:aws:kafka:us-east-1:accoutnid:cluster/test/cluster-uuid" --profile msktest

Here is my ProducerConfig code 

  Properties producerProperties = new Properties();
        producerProperties.put("bootstrap.servers", "IAM_Broker_address");
        producerProperties.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
        producerProperties.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
        producerProperties.put("sasl.jaas.config", SASL_IAM_JAAS_CONFIG_VALUE);
        producerProperties.put(ProducerConfig.CLIENT_ID_CONFIG, "kafkaproducer");
        producerProperties.put("security.protocol", "SASL_SSL");
        producerProperties.put("sasl.mechanism", "AWS_MSK_IAM");
        producerProperties
                .put("sasl.client.callback.handler.class", "software.amazon.msk.auth.iam.IAMClientCallbackHandler");
        KafkaProducer<String, String> producer = new KafkaProducer<String, String>(producerProperties);
        producer.send(new ProducerRecord<>("test", "keys", "values"));

=========

Any ideas , why isnt it working? I tried few other API calls like ListPartitions etc, which also dont seem to work. 

I'm guessing something with my ProducerConfig?

**Comment by sayantacC** [comment]
What is the value of the String constant SASL_IAM_JAAS_CONFIG_VALUE used in your ProducerConfig code ?
Based on your input, it should be similar to
 `"software.amazon.msk.auth.iam.IAMLoginModule required awsProfileName=\"msktest\";"`

**Comment by agurha** [comment]
i think i figured it out, its SSL issue. I need to generate certs etc . To answer your question - yes thats the value. 
Will update, how it goes after cert generation.

**Comment by gokul2411s** [comment]
@agurha did your fix for the SSL issue work as expected?

**Comment by gokul2411s** [comment]
Closing due to lack of response.
