### ISSUE TITLE
Enable support for regional VPC STS endpoints

### ISSUE THREAD

**Issue by dvulpe** [aws/aws-msk-iam-auth#35]
In an internet-disconnected VPC which can only reach the regional STS endpoint (sts.AWS_REGION.amazonaws.com) and not the global STS endpoint (sts.amazonaws.com) a standard Java consumer running in AWS Lambda and configured to assume an IAM role fails with the following error:
```
org.apache.kafka.common.errors.SaslAuthenticationException: 
An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: 
Failed to find AWS IAM Credentials 
[Caused by com.amazonaws.SdkClientException: 
Unable to execute HTTP request: Connect to sts.amazonaws.com:443 [sts.amazonaws.com/54.239.21.217] failed: 
connect timed out]) occurred when evaluating SASL token received from the Kafka Broker. 
Kafka Client will go to AUTHENTICATION_FAILED state.
```

One approach to fix this would be to accept an attribute for the STS region and default it to `aws-global` in case it's not provided. 
A workaround would be to configure an AWS profile with the regional STS endpoint and refer to it from the consumer configuration, but requires the filesystems to be writable (doesn't work in AWS Lambda where this consumer runs).

**Comment by sayantacC** [comment]
Thanks for reporting this. We will look into how to enable the use of STS regional endpoints.

**Comment by dvulpe** [comment]
> Thanks for reporting this. We will look into how to enable the use of STS regional endpoints.

Thanks @sayantacC. I've raised a pull request with a potential solution.

**Comment by sayantacC** [comment]
I am sorry I have not had a chance to look into the PR yet. I will get to it as soon as I can.

**Comment by sayantacC** [comment]
I left a comment on the PR. Strangely, when I used it on my test setup, it also required setting the sts endpoint in addition to the sts region. The details are in the comments on the PR. Will you have time to take a further look ?

**Comment by sayantacC** [comment]
Thanks a lot for your contribution. I have merged it in. I will update the README to reflect the new option soon.
