### ISSUE TITLE
Cross Account assume role is not working

### ISSUE THREAD

**Issue by ashemachandan** [aws/aws-msk-iam-auth#41]
Hello,

We are trying to access MSK - Account A from KafkaConnect on EKS - Account B using aws iam auth and below are the configurations that are maintained along with VPC peering, routable and security groups -

# In Account A 

IAM Role - arn:aws:iam::AccountA:role/mskclient
Policies -
``
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "kafka-cluster:*",
                "kafka:*"
            ],
            "Resource": "*"
        }
    ]
}
``
Trust -
``
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::AccountB:role/mskclient"
        ]
      },
      "Action": "sts:AssumeRole",
      "Condition": {}
    }
  ]
}
``

# In Account B 

IAM Role - arn:aws:iam::AccountB:role/mskclient
Polices - 
``
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "sts:AssumeRole",
            ],
            "Resource": "arn:aws:iam::AccountA:role/mskclient"
        }
    ]
}
``

Trust - 
``
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::AccountB:role/ec2_ssm",
          "arn:aws:iam::AccountB:role/eks-worker-node",
          "arn:aws:iam::AccountB:root"
        ]
      },
      "Action": "sts:AssumeRole",
      "Condition": {}
    }
  ]
}
``

# KafkaConnect 
``
Bootstrap servers
bootstrap.servers=b-1.xxxx.kafka.eu-west-1.amazonaws.com:9098,b-2.xxxx.kafka.eu-west-1.amazonaws.com:9098,b-3.xxxx.kafka.eu-west-1.amazonaws.com:9098
REST Listeners
rest.port=8083
rest.advertised.host.name=10.254.192.206
rest.advertised.port=8083
Plugins
plugin.path=/opt/kafka/plugins
Provided configuration
offset.storage.topic=kafka-connect-cluster-offsets
value.converter=org.apache.kafka.connect.json.JsonConverter
config.storage.topic=kafka-connect-cluster-configs
key.converter=org.apache.kafka.connect.json.JsonConverter
group.id=kafka-connect-cluster
status.storage.topic=kafka-connect-cluster-status
config.storage.replication.factor=3
offset.storage.replication.factor=3
status.storage.replication.factor=3

security.protocol=SASL_SSL
sasl.mechanism=AWS_MSK_IAM
sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required awsRoleArn="arn:aws:iam::AccountB:role/mskclient";
sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler

producer.security.protocol=SASL_SSL
producer.sasl.mechanism=AWS_MSK_IAM
producer.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required awsRoleArn="arn:aws:iam::AccountB:role/mskclient";
producer.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler

consumer.security.protocol=SASL_SSL
consumer.sasl.mechanism=AWS_MSK_IAM
consumer.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required awsRoleArn="arn:aws:iam::AccountB:role/mskclient";
consumer.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler 
``

# We have tested 3 scenarios as below 
1) Success - In Account A, KafkaConnect on EC2 in Account A connected to MSK - Account A by assuming role - arn:aws:iam::AccountA:role/mskclient
2) Failed - In Account B, KafkaConnect on EC2 in Account B failed to connect MSK - Account A by assuming role - arn:aws:iam::AccountB:role/mskclient
3) Failed - In Account B, KafkaConnect on EKS worker node failed to connect MSK - Account A by assuming role - arn:aws:iam::AccountB:role/mskclient

Failed scenarios has same errors like below so kindly let us know if this cross account role assume is supported in the current 1.1.0 release.

``
INFO [AdminClient clientId=adminclient-1] Failed authentication with b-2.dnaoi-dev-test-cluster.l0c2o1.c1.kafka.eu-west-1.amazonaws.com/192.168.2.127 ([362d44d8-58fe-48bd-a76f-0ccf4b010989]: Access denied) (org.apache.kafka.common.network.Selector:616)
[2021-09-08 18:15:28,377] ERROR [AdminClient clientId=adminclient-1] Connection to node -2 (b-2.dnaoi-dev-test-cluster.l0c2o1.c1.kafka.eu-west-1.amazonaws.com/192.168.2.127:9098) failed authentication due to: [362d44d8-58fe-48bd-a76f-0ccf4b010989]: Access denied (org.apache.kafka.clients.NetworkClient:765)
[2021-09-08 18:15:28,378] WARN [AdminClient clientId=adminclient-1] Metadata update failed due to authentication error (org.apache.kafka.clients.admin.internals.AdminMetadataManager:232)
org.apache.kafka.common.errors.SaslAuthenticationException: [362d44d8-58fe-48bd-a76f-0ccf4b010989]: Access denied
[2021-09-08 18:15:28,396] INFO App info kafka.admin.client for adminclient-1 unregistered (org.apache.kafka.common.utils.AppInfoParser:83)
[2021-09-08 18:15:28,398] INFO [AdminClient clientId=adminclient-1] Metadata update failed (org.apache.kafka.clients.admin.internals.AdminMetadataManager:235)
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1631124957248, tries=1, nextAllowedTryMs=-9223372036854775709) timed out at 9223372036854775807 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
[2021-09-08 18:15:28,398] INFO [AdminClient clientId=adminclient-1] Metadata update failed (org.apache.kafka.clients.admin.internals.AdminMetadataManager:235)
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1631124958381, tries=1, nextAllowedTryMs=-9223372036854775709) timed out at 9223372036854775807 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
[2021-09-08 18:15:28,437] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:659)
[2021-09-08 18:15:28,437] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:663)
[2021-09-08 18:15:28,438] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:669)
[2021-09-08 18:15:28,438] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectDistributed:86)
org.apache.kafka.connect.errors.ConnectException: Failed to connect to and describe Kafka cluster. Check worker's broker connection and security properties.
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:70)
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:51)
        at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:97)
        at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:80)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.SaslAuthenticationException: [362d44d8-58fe-48bd-a76f-0ccf4b010989]: Access denied
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:64)
``

**Comment by sayantacC** [comment]
Such cross account access should work. 
On the account B ec2 node could you try assuming the account A mskclient role using the [aws cli
](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sts/assume-role.html) ? 

That will tell us if there is an issue with the role setup itself.

**Comment by ashemachandan** [comment]
I have tried the below but still no luck so we have any further logs to check - 

1- EC2 IAM role assumed the cross account role 
2- Maintined only in KafkaConnect : sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required ;
3-  Trust in Account A role - 
``
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::AccountA:role/ec2_test_ssm"
      },
      "Action": "sts:AssumeRole",
      "Condition": {}
    }
  ]
}
``

# AWS ACL on Account B

aws sts assume-role --role-arn arn:aws:iam::AccountB:role/mskclient --role-session-name msk-access
{
    "AssumedRoleUser": {
        "AssumedRoleId": "AROAYAODCY7BY3YT6YJ76:msk-access",
        "Arn": "arn:aws:sts::AccountB:assumed-role/mskclient/msk-access"
    },
    "Credentials": {
        "SecretAccessKey": "XXXXXXXXX+V2J5paOmHvTnaA3FJIu67",
        "SessionToken": "XXXXXXXXXXXX//////////wEaDHDwyICpZk9+Y+9z/iKuAZV2PSMDzZy1MIDyjCrft+pV3E5jGpw28VkkogMxMOxjArv5wQoOZz/TOgOMG/1mTs6o2HZGw88kLozCtfTF5XgQllSoKf/GV+iA8vX8guHy8jiWpJ0EIPX3puYLSMNASPCCAlhT0tJECnF3dipu9GJK2V3bFJfn4ufBkOXrkKt6A+dFQnrAerkydIS2dkNy6JzGtJzuE6wlb8ghwCBvyDAD0kmZNG2OczYvI14iYSingeeJBjItpIa7ohWRavjuns+7jusLWW5Sqa4tadFAMBLot4qGo6fVx7IVKkX5vW+D/J6o",
        "Expiration": "2021-09-09T09:07:03Z",
        "AccessKeyId": "XXXXXXXXXXXX"
    }
}

**Comment by sayantacC** [comment]
I apologize for the problems you are running into:
I wanted to follow up on a few points:
* Since you are using Kafka Connect, I wanted to make sure of one thing: The `aws-msk-iam-auth` library is placed on the CLASSPATH and not on the plugin path for Kafka connect. 
* The trust in Account A role seems to only trust the `AccountB:role/ec2_test_ssm`. Is the Kafka connect process running as ec2_test_ssm role ? I suspect the problem might be to do with the identity under which the Kafka connect process is running. Would it be possible for you to call [get-caller-identity](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sts/get-caller-identity.html) in the same way as Kafka Connect ? It would validate the exact identity in Account B being used.
* Also could you enable client side DEBUG level logging ? It would help understand exactly what is happening.

I will try to duplicate your setup but sadly it will take me some time.

**Comment by ashemachandan** [comment]
Thanks Sayanta for the inputs, the configuration is working after using the new jar of version 1.1.1 and we have some gaps in understanding this assuming the role like what kind of auth the eks pod is assuming from the list below because we had believed its Web Identity but where inline specifying an AWS IAM Role for a client (sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required awsRoleArn="arn:aws:iam::AccountB:role/mskclient";) is working in our case so kindly confirm -

1) Environment variables: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.
2) Java system properties: aws.accessKeyId and aws.secretKey.
3) Web Identity Token credentials from the environment or container.
4) The default credential profiles file– typically located at ~/.aws/credentials (location can vary per platform)

**Comment by sayantacC** [comment]
If you specify the `awsRoleArn` in `sasl.jaas.config` it will try to use that role for credentials. If it cannot use that role, only then will it try Environment Variables, System Properties, Web Identities, Profile based credentials, EC2 instance or container credentials in that order.

**Comment by ashemachandan** [comment]
What we observed from the logs is the Default Credential Provider Chain looks for credentials in the above order first, if that fails then goes for `awsRoleArn` assume method and Service Account Annotation( `eks.amazonaws.com/role-arn: "arn:aws:iam::AccountB:role/mskclient`) alone is not working where `awsRoleArn`  in `sasl.jaas.config` is required to make this auth working properly for EKS POD with AWS MSK so kindly check once from your end.
