### ISSUE TITLE
Help setting up msk iam auth with kafka rest proxy

### ISSUE THREAD

**Issue by rae89** [aws/aws-msk-iam-auth#44]
Hi currently I am getting the following error when I make a request to an API Gateway that i have configured as an HTTP Proxy to an ec2 instance with the confluent kafka rest proxy: https://www.cloudkarafka.com/docs/kafkarestproxy.html

> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at io.confluent.kafkarest.extension.ContextInvocationHandler.invoke(ContextInvocationHandler.java:32)
> 	... 58 more
> Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
> 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:434)
> 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:287)
> 	at io.confluent.kafkarest.ProducerPool.buildNoSchemaProducer(ProducerPool.java:120)
> 	at io.confluent.kafkarest.ProducerPool.buildBinaryProducer(ProducerPool.java:106)
> 	at io.confluent.kafkarest.ProducerPool.<init>(ProducerPool.java:71)
> 	at io.confluent.kafkarest.ProducerPool.<init>(ProducerPool.java:60)
> 	at io.confluent.kafkarest.ProducerPool.<init>(ProducerPool.java:53)
> 	at io.confluent.kafkarest.DefaultKafkaRestContext.getProducerPool(DefaultKafkaRestContext.java:59)
> 	... 63 more
> Caused by: java.lang.IllegalArgumentException: Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set
> 	at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:143)
> 	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:108)
> 	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:94)
> 	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:134)
> 	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:73)
> 	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
> 	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:442)
> 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:423)

I have placed the msk iam auth jar in the classpath for the kafka rest proxy. 

Here is the policy I am using for the msk iam:

   ```
 "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kafka-cluster:*",
                "kafka-cluster:AlterCluster",
                "kafka-cluster:DescribeCluster"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "kafka-cluster:*",
                "kafka-cluster:DescribeGroup"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

here is my kafka-rest.properties file

> ssl.truststore.location=/tmp/kafka.client.truststore.jks
> listeners=http://0.0.0.0:8082
> zookeeper.connect=z-1.XXXXXXXXXXXXXXXXXX:2181,XXXXXXXXXXXXXXXXX:2181
> bootstrap.servers=b-2.XXXXXXXXXXXXXXXX:9098,XXXXXXXXXXXXXXX:9098
> security.protocol = SASL_SSL
> sasl.mechanism = AWS_MSK_IAM
> sasl.jaas.config = software.amazon.msk.auth.iam.IAMLoginModule required awsRoleArn="arn:aws:iam::xxxxxxxxxxxx:role/kafka_client" awsDebugCreds=true;
> sasl.client.callback.handler.class = software.amazon.msk.auth.iam.IAMClientCallbackHandler

Any thoughts on what I am missing?

**Comment by Rayshard** [comment]
How did you place the msk iam auth jar in the classpath for the kafka rest proxy?
