### ISSUE TITLE
Getting "Killed" message as response using kafka cli inside EKS pod

### ISSUE THREAD

**Issue by mikamboo** [aws/aws-msk-iam-auth#49]
Hello,

I'm trying to use the libray inside a EKS Pod. Pod is authenticated using AWS IAM for ServiceAccount. I try to create topic in my AWS MSK cluster with IAM auth enabled.

I put aws-msk-iam-auth .jar file inside kafka libs directory and aloso tried to export in CLASSPATH without succeed.

Bellow my configuration :

Kafka  : 2.8.1
aws-msk-iam-auth: 1.1.1
openjdk : 1.8.0_312

Rôle policy :

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "kafkaconnect:*",
                "kafka-cluster:*",
                "kafka:*"
            ],
            "Resource": "*"
        }
    ]
}
```

client.properties

```
security.protocol=SASL_SSL
sasl.mechanism=AWS_MSK_IAM
sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
```

CMD i run : `./bin/kafka-topics.sh --bootstrap-server $BROKER1:9098 --create --topic my-topic --command-config ./client.properties`

I got **Killed** message as response :(

Thanks for helping !

**Comment by somik47** [comment]
Can you please elaborate what exactly you did, i am also getting similar issue by using client.properties
