### ISSUE TITLE
Provide ability to specify  AWSCredentialsProvider 

### ISSUE THREAD

**Issue by rampaldheeraj** [aws/aws-msk-iam-auth#56]
Hi ,
We have a setup wherein we have an on-premise kubernetes cluster and 2 AWS Accounts, Account-A and Account-B. We have a use case where we have an AWS-SQS  in Account-A and a MSK-Cluster in Account-B . All our pods use OIDC federated tokens to access the AWS Resources and `WebIdentityTokenCredentialsProvider` as credentials provider for accessing AWS-SQS. This is a snippet from an application running in K8s cluster.

```
AmazonSQSClientBuilder.standard()
                .withRegion(properties.getSigningRegion())
                .withCredentials(new WebIdentityTokenCredentialsProvider())
                .build();
```

This all works fine because we have following environment variables configured in our pods:

```
  AWS_ROLE_ARN
  AWS_WEB_IDENTITY_TOKEN_FILE

```

The same application now needs to connect to MSK cluster hosted in Account-B. I have created a separate role (`arn:aws:iam::XXXXXXXX:role/basic/XXXXXXXXX\`) in Account-B for our application to allow it to access the MSK Cluster. 

So, now instead of 1 role , I have now 2 roles. I can programatically configure the roleArn for the SQS Client like this:

```
               WebIdentityTokenCredentialsProvider.builder()
                    .roleArn("")
                    .webIdentityTokenFile("")
                    .build();
```

Is there a way to do something similar with AWS-MSK-IAM-AUTH library? So basically I am looking for a way to configure a different `WebIdentityTokenCredentialsProvider` for iam-authentication library.

**Comment by sayantacC** [comment]
@rampaldheeraj You can configure a `KafkaProducer` programmatically by passing it the producer's properties including the parameters required for`aws-msk-iam-auth`, such as `security.protocol`,`sasl.mechanism`,`sasl.jaas.config` and `sasl.client.callback.handler.class`.

Please see this example of configuring a Kafka Producer programmatically in the [tests](https://github.com/aws/aws-msk-iam-auth/blob/main/src/test/java/software/amazon/msk/auth/iam/ProducerClientTest.java#L35). Please note that the test uses dummy data which will have to be replaced for your use case.

Also, please look at how an [IAM Roles can be specified as an argument](https://github.com/aws/aws-msk-iam-auth#specifying-an-aws-iam-role-for-a-client). 

Please let me know if this helps.

**Comment by rampaldheeraj** [comment]
@sayantacC Thanks for the quick response. I have no problem in configuring and running producers with `aws-msk-iam-auth` library. I just want to know if there's a way to configure `WebIdentityTokenCredentialsProvider` programmatically. I have explained the situation in my question above.

**Comment by sayantacC** [comment]
@rampaldheeraj I apologize for misunderstanding the question. 

I am sorry but currently the environment variables are the only way to configure the `WebIdentityTokenCredentialsProvider` in `aws-msk-iam-auth`. 

Would it be possible for you to configure the SQS client by providing the `roleArn` and `webIdentityTokenFile` to point to  the role for Account A? Then the environment variables could point to the role for Account B and could be used by the `aws-msk-iam-auth`. Is that something that would work for your scenario?

**Comment by rampaldheeraj** [comment]
@sayantacC . I can certainly try that. Thanks for the suggestion.

**Comment by rampaldheeraj** [comment]
Thanks @sayantacC . This works. But not very convenient. Instead it will be good to have the ability to specify the Credentials Provider. That way it will be explicit and clear in code about which Credentials are being used for which Service. 
Is there any way to pass credentials (AWS secret access key and Session Token) to `aws-msk-iam-auth` ?

**Comment by sayantacC** [comment]
@rampaldheeraj You could create a AWS credential profile and pass the `awsProfileName` as an argument to `sasl.jaas.config`. Please see this [sub-section in the README](https://github.com/aws/aws-msk-iam-auth#specifying-an-alternate-credential-profile-for-a-client)

**Comment by sayantacC** [comment]
I have marked this issue as an enhancement.

**Comment by s-ifti** [comment]
@sayantacCm  the awsProfileName approach is a good workaround, but profile files based approach is difficult to work with when a service has to support multi-tenant connectivity to multiple customer's owned MSK instances, in that context using an embedded JaasConfig works out well.

This enhancement request is similar to how kinesis flink connector is supporting ability to override credentials provider when using STS assume role ([link](https://github.com/awslabs/amazon-kinesis-connector-flink/blob/master/amazon-kinesis-connector-flink/src/main/java/software/amazon/kinesis/connectors/flink/config/AWSConfigConstants.java#L88)) to support connectivity to cross account kinesis streams.

One way we are able to achieve this is by adding two extra properties  providing an OIDC Token file and an assume role arn for sts crednetials provider, see following gist as an example

https://gist.github.com/s-ifti/509ffb6150ab541655313e0889a9a163

Having this feature supported will assist  SAAS developers who need to work with cross account access to MSK using IAM Roles.
