### ISSUE TITLE
IAM RBAC to Schema Registry?

### ISSUE THREAD

**Issue by tooptoop4** [aws/aws-msk-iam-auth#57]
Can I use this jar to give certain role/arn access to certain subjects in schema registry, similar to https://docs.confluent.io/platform/current/schema-registry/security/rbac-schema-registry.html ?

**Comment by sayantacC** [comment]
The `aws-msk-iam-auth` library is only for interactions with the Kafka cluster and providing users or roles access to Kafka resources such as topics or consumer groups. The [`aws-glue-schema-registry`](https://github.com/awslabs/aws-glue-schema-registry) handles the interactions with resources (registries, schemas) in glue schema registry. 
The two can be used together. 

However, if you have questions about authn/z with the glue schema registry could you open an issue with that [library](https://github.com/awslabs/aws-glue-schema-registry)? You will get answers from the experts on the glue schema registry library.

**Comment by tooptoop4** [comment]
@sayantacC  I'm interested in confluent registry not glue one
