### ISSUE TITLE
AWS SDK v2 dependency too old

### ISSUE THREAD

**Issue by jackye1995** [aws/aws-msk-iam-auth#63]
The AWS SDK v2 dependency version 2.16.74 is too old, and we have trouble using this in Glue ETL with other jars that have newer dependency version.

For example, we get this error when loading S3 SDK:

```
py4j.protocol.Py4JJavaError: An error occurred while calling o73.sql.
: java.lang.NoSuchMethodError: software.amazon.awssdk.utils.CollectionUtils.uniqueIndex(Ljava/lang/Iterable;Ljava/util/function/Function;)Ljava/util/Map;
	at software.amazon.awssdk.utils.internal.EnumUtils.uniqueIndex(EnumUtils.java:39)
	at software.amazon.awssdk.services.s3.model.ObjectCannedACL.<clinit>(ObjectCannedACL.java:40)
```

Because `CollectionUtils.uniqueIndex` is added in September 2021, but there is another CollectionUtils with the same class path that does not have this method, which is included by this jar.

Can we either update the dependency version, or relocate the SDKs in the shadow jar instead of using the original class paths?

**Comment by OneCricketeer** [comment]
If you're using Spark, there's a config option to put the user's classpath first. You can try to upgrade the necessary dependencies in your app, then see if setting that will work

**Comment by jvdadda** [comment]
SDK v2 have been recently updated in 2.26.8 (june 2024)

@sidyag Can be closed

**Comment by guanlin84** [comment]
Closing since it's fixed.
