### ISSUE TITLE
Question around MSK IAM performance limit / quota

### ISSUE THREAD

**Issue by wlaw868** [aws/aws-msk-iam-auth#70]
ref https://docs.aws.amazon.com/msk/latest/developerguide/limits.html

> A cluster that uses [IAM access control](https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html) can have up to 3000 TCP connections per broker at any given time.

> A cluster that uses [IAM access control](https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html) can accept new connections at a rate of up to 20 TCP connections per broker per second for all broker types, except for kafka.t3.small. Brokers of type kafka.t3.small are limited to 4 TCP connections per broker per second.

Does MSK provide any metrics that show the trend of new connections?

**Comment by dude0001** [comment]
For new connections search for the metric ConnectionCreationRate, it is under the [AWS/Kafka] [Broker ID, Cluster Name] namespace.

![image](https://user-images.githubusercontent.com/148839/170701631-e551ea3f-7501-4b71-b378-97b1f3884123.png)

Also, see #45 and  #61 for previous issues and extra insight into these quotas. There was an issue in MSK recently fixed where a heartbeat process would get in a bad state and repeatedly try to open new connections in a tight loop with no retry or backoff. This was causing the new connections quota to be exceed sporadically and the "Too many connects" error. If you are seeing these issues, you might want to create a support ticket to see if they can check that the fix has been applied to your cluster. See as well the documentation for some suggestions on how to configure your clients to be resilient when these quotas are exceeded https://docs.aws.amazon.com/msk/latest/developerguide/limits.html#msk-provisioned-quota.
