### ISSUE TITLE
Slow AdminClient responses leading to timeouts and failures

### ISSUE THREAD

**Issue by kppullin** [aws/aws-msk-iam-auth#73]
We have an MSK cluster with ~1750 topics and ~550 consumer groups, as well as a self hosted Kafka Connect deployment using this instance.  Upon enabling MSK IAM Auth within Kafka Connect, Kafka Connect started failing. Via the logs we discovered that the `listTopics` API call was timing out (the timeout is 30 seconds, which I believe is the default).

I built a small test application to execute `listTopics`, `listConsumerGroups`, and `describeCluster` APIs using the Kafka `AdminClient` to see if the issue was specific to kafka connect or more generalized.  In the test app I observed the same timeouts, with the `listTopic` API call needing about 35 seconds to return.

Subsequent executions of these API calls return much faster (if the connection is reused) and leads me to believe there's caching going on internally.

The question is if this behavior expected and typical? I'd prefer not have to monitor and continually increase the timeouts as the number of topics in the cluster increases, to not mask actual underlying issues by setting large timeouts, nor have such slow responses in general.  Further, is there anything I can do on my end config wise to avoid this slow start behavior?

Here's some approximate timing data for reference:

| API Call | Duration | Authentication Type |
|------------|--------------|----------------------------|
| `describeCluster` | ~50ms | Plaintext |
| `describeCluster` | 2s | MSK |
| `listConsumerGroups` | ~300ms | Plaintext |
| `listConsumerGroups` | 10s | MSK |
| `listTopics` | ~450ms | Plaintext |
| `listTopics` | 35s | MSK |

**Comment by gokul2411s** [comment]
This is a known issue for which we have a fix in place, currently undergoing deployment. The response time after the fix is applied will be much smaller and therefore unlikely to result in timeouts.

Please open a support case with MSK, so we can apply the fix to your cluster.

**Comment by kppullin** [comment]
Thanks.  I'll open a new support ticket and reference your reply.  FWIW my existing case has been making no progress for ~6 weeks and there's apparently a lack of internal knowledge of this issue/fix.

**Comment by rmetzger** [comment]
I'm affected by this issue too. Do you have an ETA for the fix for all customers?

**Comment by gokul2411s** [comment]
> I'm affected by this issue too. Do you have an ETA for the fix for all customers?

We'll try to complete deployment by end of this week (Jul 8th). Please open a support case with MSK, so we can apply the fix to your cluster.

**Comment by rmetzger** [comment]
Thanks a lot for your information. We have decided to wait for the fix to be deployed to all customers, instead of raising at ticket.

**Comment by gokul2411s** [comment]
The deployment is complete. The fix will now apply for new clusters created from this point onwards. For existing clusters, open a support case with MSK, so we can apply the fix to your cluster. FYI @rmetzger.

**Comment by rmetzger** [comment]
Oh, good to know. Thank you!

**Comment by rmetzger** [comment]
Sorry for going really off-topic: Is there a way to open a support case without buying the [Developer](https://aws.amazon.com/premiumsupport/plans/developers/) support plan?

**Comment by kppullin** [comment]
To close this out, I can confirm that the fix did solve the issue for us.

If anyone else requires this patch, I was requested to supply an update window between 10AM-5PM UK/BST time. It took ~1 week to get to this point, and another for the patch to be applied, so I'd suggest providing this information upfront for faster turn around.

Also, I had hoped the patch would be automatically applied during routine security patching of the clusters. At least for our production clusters, it was not automatically applied and will require another support ticket (we've only updated some non-production clusters thus far).
