### ISSUE TITLE
has this been tested on kafka 3.2.0 clients ?

### ISSUE THREAD

**Issue by tooptoop4** [aws/aws-msk-iam-auth#75]
https://github.com/confluentinc/kafka-images/issues/172#issuecomment-1182117896

**Comment by dude0001** [comment]
It looks like this is compiled with the 2.8.1 client (https://github.com/aws/aws-msk-iam-auth/blob/16b3c15be88ad9f4ace133e8bd5956fc2e065553/build.gradle#L42) and automated tests run with 2.2.1 (https://github.com/aws/aws-msk-iam-auth/blob/16b3c15be88ad9f4ace133e8bd5956fc2e065553/build.gradle#L57). So I think the official answer would be, no, it hasn't been tested with 3.2.0. I can share with you we are running Kafka Connect and Kafka 3.2.0, and also using this in Spark Streaming jobs and it is working.

**Comment by sidyag** [comment]
AWS internally runs tests on all Kafka versions that are made available on MSK. Those include tests on this library. This library has passed tests on all Kafka versions made available on MSK. The compile dependency in this library is for the components that it extends, and is not an indicator of the versions supported.
